spring:
  application:
    name: scalearn-backend

  data:
    mongodb:
      auto-index-creation: true
      username: root
      password: root
      database: scalearn
      port: 27017
      host: 192.168.49.1
      authentication-database: admin
server:
  port: 8082

application:
  data:
    basePath: /home/satyam/scalearndata